[package]
name = "sqlx-models-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "*", features = ["extra-traits", "full"] }
quote = "*"
convert_case = "*"

[lib]
proc-macro = true

